package repo

import (
	"context"
	"fmt"
	"log"
	"sync"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/jmoiron/sqlx"
	"github.com/rodeorm/shortener/internal/core"
)

type postgresStorage struct {
	DB               *sqlx.DB    // Драйвер подключения к СУБД
	DBName           string      // Имя БД из конфиг.файла
	ConnectionString string      // Строка подключения из конфиг.файла
	deleteQueue      chan string // канал для удаления URL
}

// InsertUser сохраняет нового пользователя или возвращает уже имеющегося в наличии
func (s postgresStorage) InsertUser(Key int) (*core.User, bool, error) {
	ctx := context.TODO()
	var isUnathorized bool
	//Ищем пользователя
	err := s.DB.GetContext(ctx, &Key, "SELECT ID from Users WHERE ID = $1", Key)

	//При любой ошибке (нет пользователя с таким ИД или передан 0 в Key) получаем нового
	if err != nil {
		isUnathorized = true
		err := s.DB.GetContext(ctx, &Key, "INSERT INTO Users (Name) VALUES ($1) RETURNING ID", time.Now().Format(time.DateTime))
		if err != nil {
			return nil, isUnathorized, err
		}
	}

	return &core.User{Key: Key}, isUnathorized, nil
}

// InsertShortURL принимает оригинальный URL, генерирует для него ключ, сохраняет соответствие оригинального URL и ключа и возвращает ключ (либо возвращает ранее созданный ключ)
func (s postgresStorage) InsertURL(URL, baseURL string, user *core.User) (string, bool, error) {
	if !core.CheckURLValidity(URL) {
		return "", false, fmt.Errorf("невалидный URL: %s", URL)
	}

	ctx := context.TODO()

	var short string

	// Проверяем на то, что ранее пользователь не сокращал URL
	// s.DB.QueryRowContext(ctx, "SELECT short from Urls WHERE original = $1", URL).Scan(&short)
	s.DB.GetContext(ctx, &short, "SELECT short from Urls WHERE original = $1", URL)
	if short != "" {
		return short, true, nil
	}
	// Вставляем новый URL
	shortKey, err := core.ReturnShortKey(5)
	if err != nil {
		return "", false, err
	}

	_, err = s.DB.ExecContext(ctx, "INSERT INTO Urls (original, short, userID) SELECT $1, $2, $3", URL, shortKey, user.Key)

	if err != nil {
		return "", false, err
	}

	return shortKey, false, nil
}

func (s postgresStorage) SelectOriginalURL(shortURL string) (string, bool, bool, error) {
	ctx := context.TODO()
	var (
		original  string
		isDeleted bool
	)

	err := s.DB.QueryRowContext(ctx, "SELECT original, isDeleted FROM Urls WHERE short = $1", shortURL).Scan(&original, &isDeleted)
	if err != nil {
		log.Println("SelectOriginalURL", err)
		return "", false, false, err
	}
	if isDeleted {
		return original, true, true, nil
	}

	if original != "" {
		return original, true, false, nil
	}

	return "", false, false, nil
}

// SelectUserURLHistory возвращает перечень соответствий между оригинальным и коротким адресом для конкретного пользователя
func (s postgresStorage) SelectUserURLHistory(user *core.User) (*[]core.UserURLPair, error) {
	urls := make([]core.UserURLPair, 0, 1)
	err := s.DB.Select(&urls, "SELECT original AS origin, short, userID AS userkey FROM Urls WHERE UserID = $1", user.Key)

	if err != nil {
		return nil, err
	}

	if len(urls) == 0 {
		return nil, fmt.Errorf("нет истории")
	}
	return &urls, nil
}

func (s postgresStorage) CloseConnection() {
	s.DB.Close()
}

func (s postgresStorage) DeleteURLs(URL string, user *core.User) (bool, error) {
	ch := make(chan string)

	urls := core.GetSliceFromString(URL)

	go func() {
		for _, url := range urls {
			ch <- url
		}
		close(ch)
	}()

	for v := range makeDeletePool(ch) {
		go s.deleteURL(v, user)
	}

	return true, nil
}

func (s postgresStorage) deleteURL(url string, user *core.User) (bool, error) {
	tx, err := s.DB.Begin()

	if err != nil {
		return false, err
	}
	defer tx.Rollback()

	stmt, err := tx.PrepareContext(context.TODO(), "UPDATE Urls SET isDeleted = true WHERE short = $1 AND userID = $2")
	if err != nil {
		return false, err
	}
	defer stmt.Close()

	_, err = stmt.ExecContext(context.TODO(), url, user.Key)
	if err != nil {
		return false, err
	}
	err = tx.Commit()
	if err != nil {
		return false, err
	}
	return true, nil
}

func makeDeletePool(inputChs ...chan string) chan string {
	outCh := make(chan string)

	go func() {
		wg := &sync.WaitGroup{}

		for _, inputCh := range inputChs {
			wg.Add(1)

			go func(inputCh chan string) {
				defer wg.Done()
				for item := range inputCh {
					outCh <- item
				}
			}(inputCh)
		}

		wg.Wait()
		close(outCh)
	}()

	return outCh
}

func (s postgresStorage) createTables(ctx context.Context) error {
	_, err := s.DB.ExecContext(ctx,
		"CREATE TABLE IF NOT EXISTS  Users"+
			"("+
			"ID INT GENERATED BY DEFAULT AS IDENTITY"+
			", PRIMARY KEY (ID)"+
			", Name TEXT NULL"+
			")"+
			"; CREATE TABLE IF NOT EXISTS  Urls"+
			"("+
			"ID INT GENERATED BY DEFAULT AS IDENTITY"+
			", PRIMARY KEY (ID)"+
			", isDeleted BOOLEAN NOT NULL DEFAULT False"+
			", UserID	INT  REFERENCES Users (ID) NOT NULL"+
			", Original TEXT NOT NULL "+
			", CorrelationID TEXT NULL"+
			", Short TEXT NOT NULL"+
			");"+
			"CREATE UNIQUE INDEX IF NOT EXISTS url_unique_idx ON Urls (original, UserID) INCLUDE (short);")
	if err != nil {
		log.Println("createTables", err)
		return err
	}
	return nil
}
