package repo

import (
	"context"
	"fmt"
	"log"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/jmoiron/sqlx"
	"github.com/rodeorm/shortener/internal/core"
)

type postgresStorage struct {
	DB                 *sqlx.DB    // Драйвер подключения к СУБД
	DBName             string      // Имя БД из конфиг.файла
	ConnectionString   string      // Строка подключения из конфиг.файла
	deleteQueue        chan string // канал для удаления URL
	preparedStatements map[string]*sqlx.Stmt
}

/*
InsertUser принимает идентификатор пользователя

Возвращает по идентификатору уже имеющегося в наличии пользователя, если такового нет, то создает нового и возвращает что пользователь не был авторизован по переданному идентификатору
*/
func (s postgresStorage) InsertUser(Key int) (*core.User, bool, error) {

	ctx := context.TODO()
	var isUnathorized bool

	//Ищем пользователя
	err := s.preparedStatements["SelectUser"].GetContext(ctx, &Key, Key)

	//При любой ошибке (нет пользователя с таким ИД или передан 0 в Key) получаем нового
	if err != nil {
		isUnathorized = true
		err = s.preparedStatements["InsertUser"].GetContext(ctx, &Key, time.Now().Format(time.DateTime))
		if err != nil {
			return nil, isUnathorized, err
		}
	}
	return &core.User{Key: Key}, isUnathorized, nil
}

/*
	InsertShortURL принимает оригинальный URL, генерирует для него ключ, сохраняет соответствие оригинального URL и ключа.

Возвращает соответствующий сокращенный урл, а также признак того, что url сократили ранее
*/
func (s postgresStorage) InsertURL(URL, baseURL string, user *core.User) (string, bool, error) {

	if !core.CheckURLValidity(URL) {
		return "", false, fmt.Errorf("невалидный URL: %s", URL)
	}

	ctx := context.TODO()
	var short string

	s.preparedStatements["SelectShortURL"].GetContext(ctx, &short, URL)
	if short != "" {
		return short, true, nil
	}

	shortKey, err := core.ReturnShortKey(5)
	if err != nil {
		return "", false, err
	}
	s.preparedStatements["InsertURL"].ExecContext(ctx, URL, shortKey, user.Key)

	return shortKey, false, nil

}

/*
	SelectOriginalURL принимает короткий урл.

Возвращает соответствующий оригинальный урл, признак, что url ранее уже сокращался; признак, что url удален
*/
func (s postgresStorage) SelectOriginalURL(shortURL string) (string, bool, bool, error) {
	ctx := context.TODO()
	var (
		original    string
		isDeleted   bool
		isShortened bool
	)

	err := s.preparedStatements["SelectOriginalURL"].QueryRowContext(ctx, shortURL).Scan(&original, &isDeleted)

	// err := s.DB.QueryRowContext(ctx, "SELECT original, isDeleted FROM Urls WHERE short = $1", shortURL).Scan(&original, &isDeleted)
	if err != nil {
		log.Println("SelectOriginalURL", err)
		return "", false, false, err
	}

	isShortened = true

	return original, isShortened, isDeleted, nil
}

// SelectUserURLHistory возвращает перечень соответствий между оригинальным и коротким адресом для конкретного пользователя
func (s postgresStorage) SelectUserURLHistory(user *core.User) (*[]core.UserURLPair, error) {
	urls := make([]core.UserURLPair, 0, 1)

	err := s.preparedStatements["SelectUserURLHistory"].Select(&urls, user.Key)

	// err := s.DB.Select(&urls, "SELECT original AS origin, short, userID AS userkey FROM Urls WHERE UserID = $1", user.Key)

	if err != nil {
		return nil, err
	}

	if len(urls) == 0 {
		return nil, fmt.Errorf("нет истории для пользователя %d", user.Key)
	}
	return &urls, nil
}

func (s postgresStorage) CloseConnection() {
	s.DB.Close()
}

func (s postgresStorage) DeleteURLs(URLs []core.URL) error {
	tx := s.DB.MustBegin()
	defer tx.Rollback()

	query := `UPDATE Urls SET isDeleted = true WHERE short = :key AND userID = :user_key`

	for _, update := range URLs {
		_, err := tx.NamedExec(query, update)
		if err != nil {
			log.Printf("Error updating ID %s: %d, %v", update.Key, update.UserKey, err)

			if rbErr := tx.Rollback(); rbErr != nil {
				log.Printf("Rollback failed: %v", rbErr)
			}
			return err
		}
	}

	if err := tx.Commit(); err != nil {
		log.Println(err)
	}
	return nil
}

func (s postgresStorage) createTables(ctx context.Context) error {
	_, err := s.DB.ExecContext(ctx,
		"CREATE TABLE IF NOT EXISTS  Users"+
			"("+
			"ID INT GENERATED BY DEFAULT AS IDENTITY"+
			", PRIMARY KEY (ID)"+
			", Name TEXT NULL"+
			")"+
			"; CREATE TABLE IF NOT EXISTS  Urls"+
			"("+
			"ID INT GENERATED BY DEFAULT AS IDENTITY"+
			", PRIMARY KEY (ID)"+
			", isDeleted BOOLEAN NOT NULL DEFAULT False"+
			", UserID	INT  REFERENCES Users (ID) NOT NULL"+
			", Original TEXT NOT NULL "+
			", CorrelationID TEXT NULL"+
			", Short TEXT NOT NULL"+
			");"+
			"CREATE UNIQUE INDEX IF NOT EXISTS url_unique_idx ON Urls (original, UserID) INCLUDE (short);")
	if err != nil {
		log.Println("createTables", err)
		return err
	}
	return nil
}
