// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rodeorm/shortener/internal/core (interfaces: StatStorager)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/rodeorm/shortener/internal/core"
)

// MockStatStorager is a mock of StatStorager interface.
type MockStatStorager struct {
	ctrl     *gomock.Controller
	recorder *MockStatStoragerMockRecorder
}

// MockStatStoragerMockRecorder is the mock recorder for MockStatStorager.
type MockStatStoragerMockRecorder struct {
	mock *MockStatStorager
}

// NewMockStatStorager creates a new mock instance.
func NewMockStatStorager(ctrl *gomock.Controller) *MockStatStorager {
	mock := &MockStatStorager{ctrl: ctrl}
	mock.recorder = &MockStatStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatStorager) EXPECT() *MockStatStoragerMockRecorder {
	return m.recorder
}

// SelectStatistic mocks base method.
func (m *MockStatStorager) SelectStatistic() (*core.ServerStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectStatistic")
	ret0, _ := ret[0].(*core.ServerStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectStatistic indicates an expected call of SelectStatistic.
func (mr *MockStatStoragerMockRecorder) SelectStatistic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectStatistic", reflect.TypeOf((*MockStatStorager)(nil).SelectStatistic))
}
